---

- name: Set configured ansible port
  set_fact:
    configured_port: "{{ ansible_port }}"

- name: Attempt connection to SSH on 22/tcp
  wait_for:
    port: "22"
    state: "started"
    host: "{{ inventory_hostname }}"
    connect_timeout: "5"
    timeout: "10"
  delegate_to: "localhost"
  ignore_errors: "yes"
  register: default_ssh

- name: Default SSH debug
  debug:
    msg: "Default SSH: {{ default_ssh }}"

- name: Evaluate status of SSH on 22/tcp
  set_fact:
    ansible_port: "22"
  when: default_ssh is defined and
        not default_ssh.failed
  register: ssh_port_set

- name: Attempt connection to SSH on nonstandard port
  wait_for:
    port: "{{ ansible_port }}"
    state: "started"
    host: "{{ inventory_hostname }}"
    connect_timeout: "5"
    timeout: "10"
  delegate_to: "localhost"
  ignore_errors: "yes"
  register: configured_ssh
  when: default_ssh is defined and
        default_ssh.state is undefined

- name: Evaluate status of SSH on nonstandard port
  debug:
    msg: "SSH port is configured properly"
  when: configured_ssh is defined and
        configured_ssh.state is defined and
        configured_ssh.state == "started"
  ignore_errors: "yes"
  register: ssh_port_set

- name: Fail if SSH port cannot be determined
  fail:
    msg: "The SSH port is neither 22 or {{ ansible_port }}."
  when: ssh_port_set is undefined

- name: Ping host
  ping:

- name: Install packages
  yum:
    name:
      - firewalld
      - python-firewall
    state: present

- name: Modify sshd_config with nonstandard port
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^Port"
    line: "Port {{ configured_port }}"
  notify: "Restart sshd"

- name: Setup SELinux to allow nonstandard SSH port
  seport:
    ports: "{{ configured_port }}"
    proto: "tcp"
    setype: "ssh_port_t"
    state: "present"

- name: Start firewalld service
  service:
    name: firewalld
    state: started

- name: Open nonstandard SSH port in firewalld
  firewalld:
    zone: public
    port: "{{ configured_port }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled

- name: Disable 22/tcp in firewalld
  firewalld:
    zone: public
    service: ssh
    permanent: yes
    immediate: yes
    state: disabled

- name: Ensure the SSH handler is run immediately
  meta: flush_handlers

- name: Modify ansible_port to use the nonstandard port
  set_fact:
    ansible_port: "{{ configured_port }}"

- name: Gather facts only at the conclusion of this role
  setup:

