---

- name: Explicitly enable public key authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PubkeyAuthentication'
    line: "PubkeyAuthentication yes"
  notify: "Restart sshd"

- name: Disable GSSAPI authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^GSSAPIAuthentication'
    line: "GSSAPIAuthentication no"
  notify: "Restart sshd"

- name: Disable X11 forwarding
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^X11Forwarding'
    line: "X11Forwarding no"
  notify: "Restart sshd"

